import "./globals.css";
import type { Metadata } from "next";
import {Header} from "@/components/Header";
import {ThemeProvider} from "@/components/theme/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
    <ThemeProvider>
      <body
        className='antialiased'
      >
          <Header/>

          <main className='min-h-screen flex-1 overflow-y-auto overflow-x-hidden py-24 px-8 bg-secondary/20 flex flex-col'>
              {children}
          </main>
      </body>
    </ThemeProvider>
    </html>
  );
}
