import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import {buttonVariants} from "@/components/ui/button";
import {homePath, ticketsPath} from "@/path";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased'
      >
        <nav className='supports-backdrop-blur:bg-background/60 fixed left-0 right-0 top-0 z-20 border-b bg-background/95 backdrop-blur w-full flex py-2.5 px-5 justify-between'>
            <div>
                 <Link  className={buttonVariants({variant:'outline'})} href={homePath()}>Home</Link>
            </div>
            <div>
                <Link className={buttonVariants({variant:'outline'})} href={ticketsPath()}>Tickets</Link>
            </div>
        </nav>
          <main className='min-h-screen flex-1 overflow-y-auto overflow-x-hidden py-24 px-8 bg-secondary/20 flex flex-col'>
              {children}
          </main>
      </body>
    </html>
  );
}
